# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 23:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TransferApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date-time transfered')),
            ],
        ),
        migrations.RemoveField(
            model_name='logs',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='logs',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_id',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Logs',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='log',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TransferApp.Article'),
        ),
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
