# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TransferApp', '0003_log_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='item_id',
            new_name='article_id',
        ),
    ]
